---
title: "Steven Cognac"
description: |

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```
<div style="line-height: .9em;">
<font size="2"> <center> [https://cognack.github.io](https://cognack.github.io/) </center> </font>

<center> <font size="2"> 1620 Laguna Street, Santa Barbara, CA 93101 | <i class="fa fa-envelope"></i> scognac@bren.ucsb.edu | <i class="fa fa-phone"></i>  978-835-0699 </font> </center> <br />

<justify> <font size="2">
I am a wetland scientist and plant biologist with six years of experience supporting ecological restoration, environmental permitting/planning, and implementing rare and invasive plant monitoring programs. I have experience conducting functional wetland assessments, jurisdictional delineations, protocol-level rare plant monitoring, and vegetation type mapping. As an enabler of the climate crisis at hand, I'm working to bridge the science communication gap between industry and the public. </font> </justify>

### Education {data-icon=graduation-cap}
<font size="2"> <left>**University of California Santa Barbara, Bren School of Environmental Science and Management** [2021-2022]{style="float:right"}<br />
Master of Environmental Data Science (MEDS) Candidate

**University of Massachusetts Amherst** [2010-2014]{style="float:right"}<br />
B.S. in Environmental Science and Sustainable Food & Farming </left></font>

### Research Experience {data-icon=laptop}

<font size="2"> <left>**Graduate Research Assistant** [Sept 2019 - Jan 2020]{style="float:right"}<br />
*Everglades Wetland Research Park, Naples FL*<br />

* Aided pilot development of a GIS-based wetland restoration model aimed at targeting restoration hot-spots in the historic extent of the Great Black Swamp region in Ohio.
* Researched storm pulsing controls and it's effect on the dynamics of the hydrologic budget and water quality parameters within a tropical constructed stormwater wetland.

</left></font>
  

### Professional Experience {data-icon=suitcase}
<font size="2"> <left>**Biologist**[Jan 2019 - May 2021]{style="float:right"}<br />
*WRA, Inc. Emeryville, California*<br />

* Collaborate with clients on environmental regulatory compliance for development, biological community restoration, water quality, and biological monitoring projects.
Lead natural resource assessments including wetland delineations, special-status species surveys, vegetation mapping, water quality monitoring and analysis, and biological monitoring.
* Manage permitting processes with agencies such as U.S. Army Corps of Engineers (Corps), California’s Regional Water Quality Control Boards, California Department of Fish and Wildlife, and the California Coastal Commission (CCC).
* Collaborate with project stakeholders, botanists, wildlife biologists, landscape architects, and engineers to aggregate and quantify information for technical and resource assessment reports.

**Wetland Scientist/Environmental Analyst**[June 2014 - June 2017]{style="float:right"}<br />
*Vanasse Hangen Brustlin, Inc. Watertown, Massachusetts*<br />

* Developed environmental permit applications in support of engineering projects for state and local transportation agencies and private development clients.
* Performed natural resource surveys including wetland and stream delineations, invasive species mapping, habitat assessments, stormwater/groundwater monitoring, and wetland assessments.
* Prepared technical reports including wetland and vernal pool functional assessments, habitat evaluations, and alternative assessments using ArcGIS to support Corps, MA Wetlands Protection Act, NEPA, and Endangered Species Act applications.
* Analyzed MassDOT Highway transportation project plans/scopes of work to identify, document, and administer environmental compliance pertaining to federal/state environmental permitting.

**Wetland Field Technician**[April 2016 - Sept 2016]{style="float:right"}<br />
*Midwest Biodiversity Institute, Hilliard, Ohio*<br />

* Executed EPA field sampling protocols at over 65 sites throughout the eastern seaboard for the 2016 National Wetland Condition Assessment. 
* Analyzed and collected hydric soil and water samples, conducted botanical inventories, characterized hydrology, and led disposition of samples.
* Handled site reconnaissance, landowner and agency coordination, and pre-sample site visits to determine presence/absence of hydric soil and/or wetland flora.

</left></font>


### Skills and Certifications
<font size="2"> <left> **Software:** ESRI ArcGIS, R, Python, Trimble Pathfinder, Google Earth Pro.<br />

**Field Skills and Equipment Management:** Corps wetland delineation, botanical dichotomous keys, Trimble GPS (GeoExplorer), YSI ProDSS/EXO2, data loggers, pressure sensors, IRGS (LI-6400XT), soil augers <br />

**Certifications:** 40-HR HAZWOPER, Basic Wetland Delineation, First Aid/CPR, SCUBA Open Water </left></font>


### Volunteer Experience
<font size="2"> <left>
**2017 – 2018:** New England Wildflower Society, Plant Conservation Volunteer Program.  Conduct surveys of rare and endangered species within Massachusetts.<br />
**2019 – 2020:** Jepson Herbarium curatorial volunteer.  Mounting Rancho Santa Ana Botanic Garden specimens from the Flora of LA collection.<br />
**2020 - 2021:** East Bay California Native Plant Society’s rare plant monitor for the Rare, Unusual, and Significant Plants of Alameda and Contra Costa Counties Program</left></font><br />


</div>
