---
title: "Kimchi Recipe"
description: |
  Overview on a quick kimchi recipe.
author:
  - name: Steven Cognac
    url: {}
date: 08-17-2021
output:
  distill::distill_article:
    self_contained: false
preview: kimchi_canned.jpeg
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Vegetable Ingredients
 - 1 napa cabbage (approx. 1-3 inch)
 - 1 Daikon (thin slices)
 - 1 Carrot (grated or matchsticks)
 - 1 bunch green onions (chopped)
 - 1/4 cup sea or kosher salt (NO IODINE)


## Mixture Ingredients - should be consistency of soggy oatmeal. Can also combine in food processor or immersion blender.

 - 3-6  cloves garlic (minced)
 - 1-2 tbs ginger (minced)
 - 1/2 onion (minced)
 - 2-4 tbs gojuchang- fermented chili paste
 - 2-3 tbs hot pepper flakes (not red pepper flakes)
 - 3-5 tbs fish sauce
 - 2-3 tbs dried shrimp (grinded)(optional)

## Steps
 1) Wash and cut up cabbage. Combine with 3-4 tbs of salt in large mixing bowl. Use another large bowl (weighted) to press on top. Wait 2-3hrs. Rinse cabbage with fresh water.  Keep a portion of the excess salty cabbage water.

 2) Prepare Mixture

 3) Drain cabbage liquid. Keep for later. Wash cabbage with fresh water!!
 
 4) Combine drained cabbage and Mixture via deep tissue massage. Make sure everything is coated.

 5) Begin canning using wide-mouth jars. Pack tightly such that no large air pockets remain. Top with excess cabbage liquid.

 6) Seal somewhat tightly and place in dark space. Contents will off-gas and liquid will likely spill out so best to keep a plate or bowl underneath just in case.





